### ISSUE TITLE
Question:  When using Coercion is it intended to alter the type of the original data?  

### ISSUE THREAD

**Issue by code4pay** [mojolicious/json-validator#153]
I just want to check as this seems to have changed from the 2.x  versions.  If I set Coercion on is it intended that it should be altering the original data?  Seems to be the case with v3.06  with numbers  which suites our use case fine but I just want to check it is not a bug before relying on it.

**Comment by jhthorsen** [comment]
The reason why it didn't change data (all the time) before was because there was a bug that prevented coercion from working before.

But the answer is yes. It's intended to change the internal representation of the data in Perl.

I think we should alter the title of this issue though, since it sounds like it's changing the data, while it's just changing the type of the data, right..?

**Comment by code4pay** [comment]
Thanks, Updated the Title, this suits us perfectly thanks.
