### ISSUE TITLE
file:// schema url behaves differently to data://

### ISSUE THREAD

**Issue by kiwiroy** [mojolicious/json-validator#172]
* JSON::Validator version: 3.14
* Perl version: 5.28
* Operating system: macOS 10.13.6 (High Sierra)

### Steps to reproduce the behavior

```perl
$schema = path(__FILE__)->sibling('schema.yaml');
$validator = JSON::Validator->new;
$validator->schema(sprintf 'file://%s', $schema);
```
where schema.yaml contains this snippet
```yaml
example:
  firstName: "Foo"
  lastName: "Bar"
  age: 6
  id: 1234
```
See [gist](https://gist.github.com/kiwiroy/e932b7371eccb7cc6982d96b95fe46c6) for more info.

### Expected behavior
No error for the `file://` url. Using `data://` and the same schema does not result in the error.

### Actual behavior
```
Can't locate object method "scheme" via package "Mojo::File" at /.../lib/Mojo/URL.pm line 134.
```
This appears to be solved by [master...kiwiroy:file-schema-id](https://github.com/mojolicious/json-validator/compare/master...kiwiroy:file-schema-id#diff-adc6881507836d26fecdde466d40eea1R496)

Using draft-7 also sidesteps the issue.

**Comment by jhthorsen** [comment]
The gist makes my head hurt. There's just too much information there. Can you make https://github.com/mojolicious/json-validator/blob/master/t/load-file.t fail instead?

**Comment by jhthorsen** [comment]
Closing this, since the issue seems to have gone stale.

**Comment by mschout** [comment]
yes, this is the same issue as jhthorsen/mojolicious-plugin-openapi#173  That is, the Mojolicious plugin is setting its own `version` attribute which puts JSON::Validator into a mode where it thinks `id` is a reference that it needs to resolve.

**Comment by karenetheridge** [comment]
I attempted to fix this in https://github.com/mojolicious/json-validator/pull/152.  The problem is that the `'$schema'` key is not being parsed out of the document after it has been read, which is what tells us what spec version to use.

The easy solution is to instantiate the JSON::Validator object with the desired version attribute (or set it yourself later): `my $jv = JSON::Validator->new->version(7)->schema(...)` -- it's important to do this before the schema is resolved, as it's not possible to go back and request a reparsing of the document with a different spec version's semantics (or erase what it thinks it learned about the document when it misparsed it the first time).
