### ISSUE TITLE
loading schema from mojo app is not documented or tested

### ISSUE THREAD

**Issue by karenetheridge** [mojolicious/json-validator#188]
I was going to submit a PR that tested this, but it sounds like you're refactoring this area, and a different decision might be best --

I noticed that the final section of `_load_schema` (where `$self->ua->server->app` is checked) is not covered by any unit tests, since Mojolicious::Plugin::OpenAPI was refactored out in commit bb11c70022a30 and t/load-from-app.t was removed.

These are the main choices (aside from doing nothing of course):

- option 1: restore t/load-from-app.t, and also document that this feature exists (a schema that cannot otherwise be found is loaded from the `ua`'s app if there is one)
- option 2: as #1, but also control this feature from a config variable set via the constructor, defaulting to off (so OpenAPI implementations can keep using this, but otherwise this normally-not-needed and probably-surprising behaviour is not enabled)
- option 3: remove the feature entirely, and modify ::OpenAPI so it fetches the schema document itself before passing it to JV.

**Comment by jhthorsen** [comment]
I think there's more of these cases. It happened when I split the repos, so instead of figuring how to do the testing properly, I cheated by adding the https://github.com/mojolicious/json-validator/blob/master/run-all-tests.sh script.

What I'm trying to say is that this functionality is tested, but unfortunately not from J::V. Let's keep this issue open as a reminder to fix it when I do the refactoring again.
