### ISSUE TITLE
Test against JSON-Schema-Test-Suite

### ISSUE THREAD

**Issue by merkys** [mojolicious/json-validator#213]
I have recently found out about [language-agnostic JSON schema test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite). It think they would be beneficial to json-validator both for regression testing and test-driven development.

**Comment by jhthorsen** [comment]
Ah! Nice to see there's new drafts in that repo :) J::V already use the official tests for draft04, but it would be fantastic to add tests for the other drafts as well.

https://github.com/mojolicious/json-validator/tree/master/t/draft4-tests

**Comment by karenetheridge** [comment]
I have recently taken over maintainership of Test::JSON::Schema::Acceptance, and am renovating it with the intention of bringing it into the JSON-Validator distribution with updated tests across all drafts.

**Comment by jhthorsen** [comment]
I've now added `t/draft[467]-acceptance.t` which optionally use Test::JSON::Schema::Acceptance. There are some tests marked as TODO though. A quick summary:

* I can't find a way to fix "float and integers are equal up to 64-bit representation limits". Please create a PR, or another issue if that is incorrect.
* I think the issue with "Location-independent identifier with base URI change in subschema" is covered in #186.
* I don't know how to do `refRemote.json` tests. I've created #224 as a follow up for that.

So since other issues exists, I'm going to close this one.

Sidenote: Annoying that the old refs aren't removed when I force push to a branch.

**Comment by merkys** [comment]
Thanks a lot @jhthorsen!
